server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://10.130.218.165:3306/tkfinance
    driver: com.mysql.jdbc.Driver
    username: TKUser
    password: pass1234
  redis:
    minIdle: 5
    maxIdle: 10
    maxTotal: 50
    maxWaitMillis: 1500
    testOnBorrow: true
    numTestsPerEvictionRun: 1024
    timeBetweenEvictionRunsMillis: 30000
    minEvictableIdleTimeMillis: 1800000
    softMinEvictableIdleTimeMillis: 10000
    testWhileIdle: true
    blockWhenExhausted: false
    host: 10.130.217.180
    port: 6379
    
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tkrs.mapper