server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/edata?serverTimezone=GMT%2B8&characterEncoding=utf8&useUnicode=true&useSSL=false
    driver: com.mysql.jdbc.Driver
    username: root
    password: Dengxian123
    
  mvc:
    static-path-pattern: /images/**
  resources:
    static-locations: file:D://Documents//Downloads//等闲
    
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tvcp.mapper
  